config/routes.rb
Rails.application.routes.draw do
	root to: "jobs#index"
  resources :boats

  devise_for :users
  resources :jobs

  post "/select-boat", to: "jobs#select_boat"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
	validates :name, uniqueness: true
end

app/models/job.rb
class Job < ApplicationRecord

	has_many :jobboats
	has_many :boats, through: :jobboats
	
	validates_presence_of :description, :origin, :destination, :quantity, :cost

	validates_numericality_of :cost, greater_than_or_equal_to: 1000

	validates :description, length: { minimum: 5 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
	def index
		@boats = Boat.all
	end

	def show
		@boat = Boat.find(params[:id])
	end

	def new
		@boat = Boat.new
	end

	def create
		@boat = Boat.new(boats_params)
		if @boat.save

			redirect_to root_path
		else
			flash[:alert] = "this name is already taken"
			redirect_to :back
		end
	end

	def destroy
		@boat = Boat.find(params[:id])
		@boat.destroy

		redirect_to root_path
		
	end

	def sam
		boat = Boat.new
		boat.name = params[:name]
		boat.location = params[:location]
		boat.quantity = params[:quantity]

		job_boat = Jobboat.new
		job_boat.boat_id = boat_id
		job_boat.job_id = params[:job_id]
		job_boat.save

		redirect_to :back
		
	end

	private

	def boats_params
		params.require(:boat).permit(:name, :location, :quantity)
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	def index
		@jobs = Job.all
	end

	def new
		@job = Job.new
	end

	def show
		@job = Job.find(params[:id])
		@boat = Boat.new
	end

	def create
		@job = Job.new(jobs_params)
		if @job.save

		redirect_to job_path(@job)
	else
		flash[:notice] = @job.errors
		redirect_to :back
	end
	end

	def select_boat
		# make a new job boat
		# set the jobboat's boat_id to the boat from the form
		# set the job_id to the job_id to the current job
		# save the job boat
		# redirect to back
		@jobboat = Jobboat.new
		@jobboat.boat_id = params["boat_id"]
		@jobboat.job_id = params["job_id"]

		@jobboat.save
		redirect_to :back

	end


	

	def edit
		@job = Job.find(params[:id])
	end

	def destroy
		@job = Job.find(params[:id])

		@job.destroy
		redirect_to root_path
	end

	def update
		@job = Job.find(params[:id])

		if @job.update(jobs_params)
			redirect_to @job
		end
	end

	private

	def jobs_params
		params.require(:job).permit(:description, :origin, :destination, :quantity, :cost, :boat_id )
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_for_field(field_name)
		flash[:notice] && flash[:notice][field_name] ? "#{field_name.capitalize} #{flash[:notice][field_name][0]}" : nil
	end
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/boats/index.html.erb
<h1>Boats:</h1>
<p>
	<h2>
		<% @boats.each do |boat| %>
		<li><%= boat.name %></li>
		<% end %>
	</h2>
</p>
<%= link_to "create a boat", new_boat_path %>

app/views/boats/new.html.erb
<%= form_for @boat do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= flash[:alert] if flash[:alert] %>
<br>
<br>

<%= f.label :location %>
<%= f.select :location, [ "Miami", "Los Angeles", "New York", "Houston", "Newark", "Tampa", "Seattle" ], :prompt => "Select Location" %>
<br>
<br>

<%= f.label :quantity %>
<%= f.text_field :quantity %>
<br>
<br>

<%= f.submit :disable_with => 'Submiting...' %>

<% end %>

app/views/boats/show.html.erb
<%= @boat.name %>
<%= link_to "Delete a boat", boat_path(@boat), method: :delete %>

app/views/jobs/_form.html.erb
<div class="jobForm">

	<%= form_for @job do |f| %>

		<%= f.label :description %> <br>
		<%= f.text_area :description %> <%= flash_for_field("description") %>

		<br>
		<br>

		<%= f.label :origin %>
		<%= f.select :origin, [ "Miami", "Los Angeles", "New York", "Houston", "Newark", "Tampa", "Seattle" ], :prompt => "Select Origin" %> <%= flash_for_field("origin") %>

		<br>
		<br>

		<%= f.label :destination %>
		<%= f.select :destination, [ "Cincinnati", "Texas City", "Cleveland", "Miami", "New York", "Houston"], :prompt => "Select Destination" %> <%= flash_for_field("destination") %>

		<br>
		<br>

		<%= f.label :quantity %>
		<%= f.select :quantity, options_for_select(1..10), :prompt => "Select Quantity" %> <%= flash_for_field("quantity") %>

		<br>
		<br>

		<%= f.label :cost %>
		<%= f.text_field :cost, :prompt => "0" %> <%= flash_for_field("cost") %>
		<br>
		<br>

		<%= f.submit %>
	<% end %>

</div>



<script>
 var initialModal = new Custombox.modal({
      content: {
        effect: 'fadein',
        target: '.jobForm'
      }
    });
    initialModal.open();
</script>

app/views/jobs/edit.html.erb
<%= render "form" %>

app/views/jobs/index.html.erb
<h1>This is a index action page of Jobs controller</h1>
<ul>

	<% @jobs.each do |job| %>
		<li>
			<%= link_to job.description, job_path(job) %>
		</li>
	<% end %>
</ul>

<%= link_to "Create a new job", new_job_path %>

app/views/jobs/new.html.erb
<%= render "form" %>

app/views/jobs/show.html.erb
<table>
	<thead>
		<tr>
			<th>Description</th>
			<th>Origin</th>	
			<th>Destination</th>	
			<th>Quantity</th>	
			<th>Cost</th>
			<th>Boats</th>	
		</tr>
	</thead>

	<tbody>

		<tr>
			<td><h4> <%= @job.description %> </h4></td>
			<td><h4> <%= @job.origin %> </h4></td>
			<td><h4> <%= @job.destination %> </h4></td>
			<td><h4> <%= @job.quantity %> </h4></td>
			<td><h4> <%= number_to_currency@job.cost %> </h4></td>
			<td><h4> <%= @job.boats.map(&:name).join(", ") %></h4></td>
	
			<td><h4> <%= link_to "delete", job_path, method: :delete %> </h4></td>
			<td><h4> <%= link_to "Edit", edit_job_path %></h4></td>

		</tr>
	</tbody>
</table>	

<%= form_tag("/select-boat") do %>
	<%= select_tag "boat_id", options_for_select(Boat.where(location: @job.origin).map { |boat| [boat.name, boat.id]}) %>
	<%= hidden_field_tag "job_id", @job.id %>
	<%= submit_tag "Submit", :disable_with => 'Submiting...' %>
<% end %>


	<div class="create_button"> <%= link_to "create a boat", new_boat_path %>
	</div>





<h4> <%= link_to "Go back", root_path %></h4>

app/views/layouts/_navbar.html.erb
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Express shipping", root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

          <ul class="nav navbar-nav navbar-right">

            <% if current_user %>

            <li> 
             <%= link_to current_user.email, root_path %>
            </li>
            <li>
              <%= link_to "Sign out", destroy_user_session_path,  method: :DELETE %>
            </li>

            <% else %>

            <li>
            <%= link_to 'Sign up', new_user_registration_path %></li>
            <li>
              <%= link_to "Sign in", user_session_path  %>
            </li>
            <li>
            <% end %>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shipping</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <%= render "layouts/navbar" %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>